name: Docker Deploy

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: techmatt101
          password: ${{ secrets.DOCKER_TOKEN }}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Extract metadata for Docker
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: techmatt101/photo-home-panel

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: techmatt101/photo-home-panel:latest
